# Generated by Django 4.0.3 on 2022-03-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('ena', models.IntegerField()),
                ('di', models.IntegerField()),
                ('encA', models.IntegerField()),
                ('encB', models.IntegerField()),
            ],
        ),
    ]
